- name: Create deployment user
  user:
    name: "{{ deployer_user.name }}"
    shell: /bin/bash
    state: present
    generate_ssh_key: yes

- name: "Ensures /home/{{ deployer_user.name }} exists"
  file:
    path: "/home/{{ deployer_user.name }}"
    state: directory
    owner: "{{ deployer_user.name }}"
    group: "{{ deployer_user.group }}"

- name: "Set proper acl flags for {{ deployer_user.name }}"
  acl:
    path: "/home/{{ deployer_user.name }}"
    entry: "u:{{ deployer_user.name }}:rwx"
    state: present
    recursive: yes
    default: yes

- name: set proper acl flags for www-data group
  acl:
    path: "/home/{{ deployer_user.name }}"
    entry: "g:{{ deployer_user.group }}:rx"
    state: present
    recursive: yes
    default: yes

- name: "Ensures {{ project_location }} exists"
  file:
    path: "{{ project_location }}"
    state: directory
    group: "{{ deployer_user.group }}"
    owner: "{{ deployer_user.name }}"

- name: "Ensure /home/{{ deployer_user.name }}/.ssh exists"
  file:
    path: "/home/{{ deployer_user.name }}/.ssh"
    state: directory
    owner: "{{ deployer_user.name }}"

- name: Add  deployer public ssh key
  authorized_key:
    user: "{{ deployer_user.name }}"
    key: "{{ public_key }}"
    state: present
  loop: "{{ deployer_user.public_keys }}"
  loop_control:
    loop_var: public_key