- name: Update apt keys
  command: apt-key update

- name: Update apt cache
  apt: update_cache=yes

- name: Run apt upgrade
  apt: upgrade=yes

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: Do full upgrade
  apt:
    upgrade: full

- name: Installs curl, wget, and git
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - curl
    - git
    - unzip
    - mercurial
    - make
    - binutils
    - bison
    - gcc
    - build-essential
    - libssl-dev
    - acl
    - unattended-upgrades

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic
