- name: make sure nginx is installed
  apt:
    name: "nginx"
    state: latest

- name: "Add site file for {{ domain_names | join(' ')}}"
  template:
    # it accepts [php, static] so far
    src: "{{ site_template_name }}-site.j2"
    dest: "/etc/nginx/sites-available/{{ domain_names[0] }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Link {{ domain_names[0] }} in /etc/nginx/sites-enabled"
  file:
    src: "/etc/nginx/sites-available/{{ domain_names[0] }}"
    dest: "/etc/nginx/sites-enabled/{{ domain_names[0] }}"
    state: link

- name: "remove default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: restrt nginx
  service:
    name: nginx
    state: restarted