- name: Install composer
  shell: "{{ install_command }}"
  loop:
    - curl -s https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
  loop_control:
    loop_var: install_command