- name: Install the MySQL packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev

- name: Start msql service
  service:
    name: mysql
    state: started

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
  with_items:
    - localhost

- name: Create .my.cnf with new credentials
  template:
    src: files/.my.cnf.j2
    dest: /root/.my.cnf

- name: Ensure Anonymous user(s) are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Restart msql service
  service:
    name: mysql
    state: restarted

- name: Create new database {{ database.name }}
  mysql_db:
    name: "{{ database.name }}"
    state: present
    encoding: "{{ database.encoding | default('utf8') }}"

- name: Create new user {{ database.user.name }} for database {{ database.name }}
  mysql_user:
    name: "{{ database.user.name }}"
    password: "{{ database.user.password }}"
    priv: "{{ database.name }}".*:ALL
    host: "{{ database.user.host }}"
    state: present
    