- name: Configure ufw defaults
  ufw: direction={{ ufw_rule.direction }} policy={{ ufw_rule.policy }}
  loop:
    - { direction: 'incoming', policy: 'reject' }
    - { direction: 'outgoing', policy: 'allow' }
  loop_control:
    loop_var: ufw_rule

- name: Configure ufw rules
  ufw: rule={{ ufw_rule.rule }} port={{ ufw_rule.port }} proto={{ ufw_rule.proto }}
  loop:
    - { rule: 'limit', port: '22', proto: 'tcp' }
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }
  loop_control:
    loop_var: ufw_rule

- name: Enable ufw logging
  ufw: logging=on

- name: Enable ufw
  ufw: state=enabled

- name: Restart ufw
  service:
    name: ufw
    state: restarted