- name: Install php-7.0
  apt:
    name: php7.0
    state: latest

- name: Install php modules
  apt:
    name: "{{ package_name }}"
    state: latest
  loop:
    - php7.0-mysql
    - php7.0-curl
    - php7.0-json
    - php7.0-fpm
    - php7.0-opcache
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-mcrypt
    - php7.0-gd
    - php7.0-xmlrpc
    - php7.0-ctype
  loop_control:
    loop_var: package_name
